services:
  - type: web
    name: activity-tracker
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d3qfv5m3jp1c738jh1k0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: activity_tracker_bfkx
      - key: DB_USERNAME
        value: activity_tracker_bfkx_user
      - key: DB_PASSWORD
        value: yEb0us1t4HhjPyUfTd7gf152HOvNMrLU
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_STACK
        value: single
      - key: LOG_SINGLE_FILE
        value: laravel.log
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://activity-tracker-n7w9.onrender.com
    healthCheckPath: /
    plan: starter
